### ISSUE TITLE
go-mpv not fount

### ISSUE THREAD

**Issue by auosun** [wildeyedskies/stmp#18]
../../go/pkg/mod/github.com/yourok/go-mpv@v0.0.0-20160721123233-ecdfd901e332/mpv/consts.go:3:10: fatal error: 'mpv/client.h' file not found
#include <mpv/client.h>
         ^~~~~~~~~~~~~~
1 error generated.

**Comment by auosun** [comment]
https://github.com/yourok/go-mpv/mpv not found this repo. i can't go build this. sorry for my unclear expression

**Comment by wildeyedskies** [comment]
Sorry, I'll try to provide more specific instructions. What operating system or distro are you using?

**Comment by second2falcon** [comment]
> You gotta install mpv-dev or libmpv-dev if you're on Linux. If you've got an M1 mac I haven't figured out how to get native MPV working yet

Shouldn't macOS be able to use x86 through Rosetta on Apple Silicon (M1, etc)?

**Comment by second2falcon** [comment]
> You gotta install mpv-dev or libmpv-dev if you're on Linux. If you've got an M1 mac I haven't figured out how to get native MPV working yet

I have mpv installed via brew, but it still can't find it (I think because it's looking in the wrong place)

**Comment by dweymouth** [comment]
@second2falcon I am currently developing a Go-based Subsonic desktop client that also uses libmpv. You may find my build instructions for Mac useful. I imagine if you set the same environment variables the stmp build will worlk too. FYI I have successfully built on M1 Mac with the Homebrew mpv package. https://github.com/dweymouth/supersonic

**Comment by second2falcon** [comment]
@dweymouth it compiled fine now, but now I get a different error
```
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100e04844]

goroutine 1 [running]:
main.main()
	/Users/second2falcon/stmp/stmp.go:44 +0x154
```

@wildeyedskies any idea what this means?

**Comment by second2falcon** [comment]
I forgot to write an update here, but I got it working a while ago.

iirc I just deleted the folder, compiled again and it worked fine.

also @dweymouth I read on your repo that you are looking for M1 compilers. I'd be down, just tag or contact me.
